export const upsertQueryMap = {
  client_map: `INSERT INTO
fund.client_master (
id,
client_code,
client_name,
client_type,
client_pan,
client_tin,
client_address,
pin,
city,
state,
country,
contact_number,
client_logo_link,
agreement_date,
lei_code,
lei_code_validity,
kra_type,
kra_login_id,
kra_username,
kra_password,
kra_pos_code,
ckyc_userid,
ckyc_username,
ckyc_password,
ckyc_institution_code
) 
select
coalesce(cm.id, case when length(tt.client_code)=3 then (ASCII(substring(tt.client_code,1,1))::text||ASCII(substring(tt.client_code,2,1))::text||ASCII(substring(tt.client_code,3,1))::text)::bigint else nextval('fund.client_master_id_seq'::regclass) end),
coalesce(cm.client_code, tt.client_code),
tt.client_name,
coalesce(tt.type,'Limited Company'),
tt.pan,
tt.tin,
tt.address,
tt.pin,
tt.city,
tt.state,
tt.country,
tt.contact_number,
tt.company_logo,
to_date(tt.agreement_date, 'DD-MM-YYYY') agreement_date,
tt.lei_code,
to_date(tt.lei_code_validity, 'DD-MM-YYYY') lei_code_validity,
tt.kra_type,
tt.kra_login_id,
tt.kra_username,
tt.kra_password,
tt.kra_pos_code,
tt.ckyc_userid,
tt.ckyc_username,
tt.ckyc_password,
tt.ckyc_institution_code
from
fund.client_master cm
right join stg.client_map tt on cm.client_code = tt.client_code
WHERE cm.client_code = $1 
AND(cm.created_by not in ('finexdistsvc','xaltssvc') or cm.last_updated_by not in ('finexdistsvc','xaltssvc'))
ON CONFLICT(id) DO
UPDATE
set
(
client_name,
client_type,
client_pan,
client_tin,
client_address,
pin,
city,
state,
country,
contact_number,
client_logo_link,
agreement_date,
lei_code,
lei_code_validity,
kra_type,
kra_login_id,
kra_username,
kra_password,
kra_pos_code,
ckyc_userid,
ckyc_username,
ckyc_password,
ckyc_institution_code
) =(
EXCLUDED.client_name,
EXCLUDED.client_type,
EXCLUDED.client_pan,
EXCLUDED.client_tin,
EXCLUDED.client_address,
EXCLUDED.pin,
EXCLUDED.city,
EXCLUDED.state,
EXCLUDED.country,
EXCLUDED.contact_number,
EXCLUDED.client_logo_link,
EXCLUDED.agreement_date,
EXCLUDED.lei_code,
EXCLUDED.lei_code_validity,
EXCLUDED.kra_type,
EXCLUDED.kra_login_id,
EXCLUDED.kra_username,
EXCLUDED.kra_password,
EXCLUDED.kra_pos_code,
EXCLUDED.ckyc_userid,
EXCLUDED.ckyc_username,
EXCLUDED.ckyc_password,
EXCLUDED.ckyc_institution_code
);`,
  fund_scheme_map: `INSERT INTO
FUND.FUND_SCHEME_MASTER(
ID,
CLIENT_ID,
FUND_CODE,
FUND_NAME,
FUND_SHORT_NAME,
BUSINESS_TYPE,
SERVICE_MODEL,
FUND_CATEGORY,
FUND_SUBCATEGORY,
FUND_NATURE,
FUND_FACEVALUE,
CURRENCY,
FUND_PERIOD,
FUND_REGISTRATION_NUMBER,
FUND_ISIN_NUMBER,
FUND_DEPOSITORY_TYPE,
FUND_DPCLID,
FUND_START_DATE,
FUND_INITIAL_CONTRIBUTION_START_DATE,
FUND_INITIAL_CONTRIBUTION_CLOSE_DATE,
FUND_END_DATE,
FUND_MATURITY_DATE,
FUND_MAX_INVESTORS,
FUND_INITIAL_CONTRIBUTION_AMOUNT,
FUND_INITIAL_CONTRIBUTION_PERCENTAGE,
FUND_SIZE_CORPUS,
FUND_SPONSOR_NAME,
FUND_INVESTMENT_MANAGER,
FUND_TRUSTEE_NAME,
TAX_ADVISOR_NAME,
LEGAL_ADVISOR_NAME,
FUND_CUSTODIAN_CODE,
FUND_ACCOUNTANT_NAME,
FUND_ACCOUNTANT_EMAIL,
FUND_ACCOUNTANT_CONTACT_NUMBER,
TRANSFER_AGENT_NAME,
TRANSFER_AGENT_ACCOUNTANT_EMAIL,
TRANSFER_AGENT_CONTACT_NUMBER,
FUND_RTA_CODE,
FUND_PREVIOUS_DATE,
FUND_CURRENT_DATE,
FUND_NEXT_DATE,
FUND_PREVIOUS_YEAR_END,
FUND_CURRENT_YEAR_END,
PREV_NAV_DATE,
NAV_FREQUENCY,
NEXT_NAV_DATE,
NAV_PUBLISH_TYPE,
PREV_NAV_PUB_DATE,
NAV_PUB_FREQUENCY,
NEXT_NAV_PUB_DATE,
FUND_PL_COMP_METHOD,
VALUATION_SEQUENCE,
UNIT_DECIMALS,
ROUND_METHOD,
ROUND_DECIMALS,
NAV_DECIMALS,
AMOUNT_DECIMALS,
FUND_DD_NOTICE_PERIOD,
FUND_DD_PENALTY_CHARGES,
FUND_TOPUP_TREATMENT,
FUND_DD_TREATMENT,
FUND_MANAGEMENT_FEE,
FUND_ADDITIONAL_FEE,
SETUP_FEE_PERCENT,
FUND_TRUSTEE_FEE,
OPERATING_EXPENSES,
GOODS_SERVICE_TAX_PERCENT,
DEFAULTER_PENALTY,
FUND_COMMITMENT_APPLICABILITY,
PREFERRED_RATE_OF_RETURN,
HURDLE_RATE,
HIGH_WATER_MARK,
HURDLE_START_DATE,
GP_SHARING_RATION,
DISTRIBUTION_FREQUENCY,
FOREX_SOURCE,
NAV_RATIO_METHOD,
IS_ACTIVE,
IS_DORMANT,
DORMANT_DATE,
FUND_STAMP_DUTY_BOURNE,
pan_or_tin,
domicile
)
SELECT
distinct COALESCE(
FS.ID,
case when length(tt.client_code)=2 then (ASCII(substring(tt.client_code,1,1))::text||ASCII(substring(tt.client_code,2,1))::text||ASCII(substring(tt.client_code,3,1))::text||ASCII(substring(upper(tt.fund_code),1,1))::text||ASCII(substring(upper(tt.fund_code),2,1))::text)::bigint else nextval('fund.fund_scheme_master_id_seq'::regclass) end
),
COALESCE(FS.CLIENT_ID, CM2.ID) CLIENT_ID,
tt.FUND_CODE,
tt.FUND_NAME FUND_NAME,
tt.FUND_SHORT_NAME,
tt.FUND_BUSINESS_TYPE FUND_BUSINESS_TYPE,
tt.SERVICE_MODEL,
tt.FUND_CATEGORY,
tt.FUND_SUB_CATEGORY FUND_SUB_CATEGORY,
tt.FUND_NATURE FUND_NATURE,
tt.FUND_FACE_VALUE,
tt.FUND_CURRENCY FUND_CURRENCY,
tt.FUND_PERIOD,
tt.FUND_REGISTRATION_NUMBER,
tt.FUND_ISIN_NUMBER,
tt.FUND_DEPOSITORY_TYPE,
tt.FUND_DP_ID,
TO_DATE(tt.FUND_START_DATE1,'DD-MM-YYYY'),
TO_DATE(
tt.FUND_INITIAL_CONTRIBUTION_START_DATE,
'DD-MM-YYYY'
),
TO_DATE(
tt.FUND_INITIAL_CONTRIBUTION_CLOSE_DATE,
'DD-MM-YYYY'
),
TO_DATE(tt.FUND_END_DATE, 'DD-MM-YYYY'),
TO_DATE(tt.FUND_MATURITY_DATE, 'DD-MM-YYYY'),
tt.FUND_MAX_INVESTORS,
tt.FUND_INITIAL_CONTRIBUTION_AMOUNT :: numeric,
tt.FUND_INITIAL_CONTRIBUTION_PERCENTAGE :: numeric,
tt.FUND_SIZE,
tt.FUND_SPONSOR_NAME,
tt.FUND_INVESTMENT_MANAGER,
tt.FUND_TRUSTEE_NAME,
tt.TAX_ADVISOR_NAME,
tt.LEGAL_ADVISOR_NAME,
tt.FUND_CUSTODIAN_CODE,
tt.FUND_ACCOUNTANT_NAME,
tt.FUND_ACCOUNTANT_EMAIL,
tt.FUND_ACCOUNTANT_CONTACT_NUMBER,
tt.TRANSFER_AGENT_NAME,
tt.TRANSFER_AGENT_ACCOUNTANT_EMAIL,
tt.TRANSFER_AGENT_CONTACT_NUMBER,
tt.FUND_RTA_CODE,
TO_DATE(tt.FUND_PREVIOUS_DATE, 'DD-MM-YYYY'),
TO_DATE(tt.FUND_CURRENT_DATE, 'DD-MM-YYYY'),
TO_DATE(tt.FUND_NEXT_DATE, 'DD-MM-YYYY'),
tt.FUND_PREVIOUS_YEAR_END,
tt.FUND_CURRENT_YEAR_END,
TO_DATE(tt.PREV_NAV_DATE_, 'DD-MM-YYYY'),
tt.NAV_FREQUENCY,
TO_DATE(tt.NEXT_NAV_DATE, 'DD-MM-YYYY'),
tt.NAV_PUBLISH_TYPE,
TO_DATE(tt.PREV_NAV_PUB_DATE, 'DD-MM-YYYY'),
tt.NAV_PUB_FREQUENCY,
TO_DATE(tt.NEXT_NAV_PUB_DATE, 'DD-MM-YYYY'),
tt.FUND_PL_COMP_METHOD,
tt.VALUATION_SEQUENCE,
tt.UNIT_DECIMALS,
tt.ROUND_METHOD_,
tt.ROUND_DECIMALS,
tt.NAV_DECIMALS,
tt.AMOUNT_DECIMALS,
tt.FUND_DD_NOTICE_PERIOD,
tt.FUND_DD_PENALTY_CHARGES,
tt.FUND_TOPUP_TREATMENT,
tt.FUND_DD_TREATMENT,
tt.FUND_MANAGEMENT_FEE,
tt.FUND_ADDITIONAL_FEE,
tt.SETUP_FEE_PERCENTAGE,
tt.FUND_TRUSTEE_FEE,
tt.OPERATING_EXPENSES,
tt.GST_PERCENTAGE :: numeric,
tt.DEFAULTER_PENALTY,
tt.FUND_COMMITMENT_APPLICABILITY_,
tt.PREFERRED_RATE_OF_RETURN,
tt.HURDLE_RATE_,
tt.HIGH_WATER_MARK,
tt.HURDLE_START_DATE_,
tt.GP_SHARING_RATION,
tt.DISTRIBUTION_FREQUENCY,
tt.FOREX_SOURCE,
tt.NAV_RATIO_METHOD,
tt.IS_ACTIVE :: boolean,
tt.DORMANT_FLAG :: boolean,
TO_DATE(tt.DORMANT_DATE, 'DD-MM-YYYY'),
tt.FUND_STAMP_DUTY_BOURNE,
tt.pan_or_tin,
tt.fund_domicile
FROM
FUND.FUND_SCHEME_MASTER FS
JOIN FUND.CLIENT_MASTER CM1 ON FS.CLIENT_ID = CM1.ID
RIGHT JOIN STG.FUND_SCHEME_MAP tt ON tt.CLIENT_CODE = CM1.CLIENT_CODE
and tt.fund_code = FS.fund_code
JOIN FUND.CLIENT_MASTER CM2 ON tt.CLIENT_CODE = CM2.CLIENT_CODE
WHERE tt.client_code = $1
AND ($2 IS NULL OR tt.fund_code = $2) 
AND (cm1.created_by  not  in ('finexdistsvc','xaltssvc') or cm1.last_updated_by  not in ('finexdistsvc','xaltssvc'))
and (cm2.created_by  not in ('finexdistsvc','xaltssvc') or cm2.last_updated_by  not in ('finexdistsvc','xaltssvc'))
and (fs.created_by not in ('finexdistsvc','xaltssvc') or fs.last_updated_by not in ('finexdistsvc','xaltssvc'))
ON CONFLICT(ID) DO
UPDATE
SET
(
FUND_CODE,
FUND_NAME,
FUND_SHORT_NAME,
BUSINESS_TYPE,
SERVICE_MODEL,
FUND_CATEGORY,
FUND_SUBCATEGORY,
FUND_NATURE,
FUND_FACEVALUE,
CURRENCY,
FUND_PERIOD,
FUND_REGISTRATION_NUMBER,
FUND_ISIN_NUMBER,
FUND_DEPOSITORY_TYPE,
FUND_DPCLID,
FUND_START_DATE,
FUND_INITIAL_CONTRIBUTION_START_DATE,
FUND_INITIAL_CONTRIBUTION_CLOSE_DATE,
FUND_END_DATE,
FUND_MATURITY_DATE,
FUND_MAX_INVESTORS,
FUND_INITIAL_CONTRIBUTION_AMOUNT,
FUND_INITIAL_CONTRIBUTION_PERCENTAGE,
FUND_SIZE_CORPUS,
FUND_SPONSOR_NAME,
FUND_INVESTMENT_MANAGER,
FUND_TRUSTEE_NAME,
TAX_ADVISOR_NAME,
LEGAL_ADVISOR_NAME,
FUND_CUSTODIAN_CODE,
FUND_ACCOUNTANT_NAME,
FUND_ACCOUNTANT_EMAIL,
FUND_ACCOUNTANT_CONTACT_NUMBER,
TRANSFER_AGENT_NAME,
TRANSFER_AGENT_ACCOUNTANT_EMAIL,
TRANSFER_AGENT_CONTACT_NUMBER,
FUND_RTA_CODE,
FUND_PREVIOUS_DATE,
FUND_CURRENT_DATE,
FUND_NEXT_DATE,
FUND_PREVIOUS_YEAR_END,
FUND_CURRENT_YEAR_END,
PREV_NAV_DATE,
NAV_FREQUENCY,
NEXT_NAV_DATE,
NAV_PUBLISH_TYPE,
PREV_NAV_PUB_DATE,
NAV_PUB_FREQUENCY,
NEXT_NAV_PUB_DATE,
FUND_PL_COMP_METHOD,
VALUATION_SEQUENCE,
UNIT_DECIMALS,
ROUND_METHOD,
ROUND_DECIMALS,
NAV_DECIMALS,
AMOUNT_DECIMALS,
FUND_DD_NOTICE_PERIOD,
FUND_DD_PENALTY_CHARGES,
FUND_TOPUP_TREATMENT,
FUND_DD_TREATMENT,
FUND_MANAGEMENT_FEE,
FUND_ADDITIONAL_FEE,
SETUP_FEE_PERCENT,
FUND_TRUSTEE_FEE,
OPERATING_EXPENSES,
GOODS_SERVICE_TAX_PERCENT,
DEFAULTER_PENALTY,
FUND_COMMITMENT_APPLICABILITY,
PREFERRED_RATE_OF_RETURN,
HURDLE_RATE,
HIGH_WATER_MARK,
HURDLE_START_DATE,
GP_SHARING_RATION,
DISTRIBUTION_FREQUENCY,
FOREX_SOURCE,
NAV_RATIO_METHOD,
IS_ACTIVE,
IS_DORMANT,
DORMANT_DATE,
FUND_STAMP_DUTY_BOURNE,
pan_or_tin,
domicile
) = (
EXCLUDED.FUND_CODE,
EXCLUDED.FUND_NAME,
EXCLUDED.FUND_SHORT_NAME,
EXCLUDED.BUSINESS_TYPE,
EXCLUDED.SERVICE_MODEL,
EXCLUDED.FUND_CATEGORY,
EXCLUDED.FUND_SUBCATEGORY,
EXCLUDED.FUND_NATURE,
EXCLUDED.FUND_FACEVALUE,
EXCLUDED.CURRENCY,
EXCLUDED.FUND_PERIOD,
EXCLUDED.FUND_REGISTRATION_NUMBER,
EXCLUDED.FUND_ISIN_NUMBER,
EXCLUDED.FUND_DEPOSITORY_TYPE,
EXCLUDED.FUND_DPCLID,
EXCLUDED.FUND_START_DATE,
EXCLUDED.FUND_INITIAL_CONTRIBUTION_START_DATE,
EXCLUDED.FUND_INITIAL_CONTRIBUTION_CLOSE_DATE,
EXCLUDED.FUND_END_DATE,
EXCLUDED.FUND_MATURITY_DATE,
EXCLUDED.FUND_MAX_INVESTORS,
EXCLUDED.FUND_INITIAL_CONTRIBUTION_AMOUNT,
EXCLUDED.FUND_INITIAL_CONTRIBUTION_PERCENTAGE,
EXCLUDED.FUND_SIZE_CORPUS,
EXCLUDED.FUND_SPONSOR_NAME,
EXCLUDED.FUND_INVESTMENT_MANAGER,
EXCLUDED.FUND_TRUSTEE_NAME,
EXCLUDED.TAX_ADVISOR_NAME,
EXCLUDED.LEGAL_ADVISOR_NAME,
EXCLUDED.FUND_CUSTODIAN_CODE,
EXCLUDED.FUND_ACCOUNTANT_NAME,
EXCLUDED.FUND_ACCOUNTANT_EMAIL,
EXCLUDED.FUND_ACCOUNTANT_CONTACT_NUMBER,
EXCLUDED.TRANSFER_AGENT_NAME,
EXCLUDED.TRANSFER_AGENT_ACCOUNTANT_EMAIL,
EXCLUDED.TRANSFER_AGENT_CONTACT_NUMBER,
EXCLUDED.FUND_RTA_CODE,
EXCLUDED.FUND_PREVIOUS_DATE,
EXCLUDED.FUND_CURRENT_DATE,
EXCLUDED.FUND_NEXT_DATE,
EXCLUDED.FUND_PREVIOUS_YEAR_END,
EXCLUDED.FUND_CURRENT_YEAR_END,
EXCLUDED.PREV_NAV_DATE,
EXCLUDED.NAV_FREQUENCY,
EXCLUDED.NEXT_NAV_DATE,
EXCLUDED.NAV_PUBLISH_TYPE,
EXCLUDED.PREV_NAV_PUB_DATE,
EXCLUDED.NAV_PUB_FREQUENCY,
EXCLUDED.NEXT_NAV_PUB_DATE,
EXCLUDED.FUND_PL_COMP_METHOD,
EXCLUDED.VALUATION_SEQUENCE,
EXCLUDED.UNIT_DECIMALS,
EXCLUDED.ROUND_METHOD,
EXCLUDED.ROUND_DECIMALS,
EXCLUDED.NAV_DECIMALS,
EXCLUDED.AMOUNT_DECIMALS,
EXCLUDED.FUND_DD_NOTICE_PERIOD,
EXCLUDED.FUND_DD_PENALTY_CHARGES,
EXCLUDED.FUND_TOPUP_TREATMENT,
EXCLUDED.FUND_DD_TREATMENT,
EXCLUDED.FUND_MANAGEMENT_FEE,
EXCLUDED.FUND_ADDITIONAL_FEE,
EXCLUDED.SETUP_FEE_PERCENT,
EXCLUDED.FUND_TRUSTEE_FEE,
EXCLUDED.OPERATING_EXPENSES,
EXCLUDED.GOODS_SERVICE_TAX_PERCENT,
EXCLUDED.DEFAULTER_PENALTY,
EXCLUDED.FUND_COMMITMENT_APPLICABILITY,
EXCLUDED.PREFERRED_RATE_OF_RETURN,
EXCLUDED.HURDLE_RATE,
EXCLUDED.HIGH_WATER_MARK,
EXCLUDED.HURDLE_START_DATE,
EXCLUDED.GP_SHARING_RATION,
EXCLUDED.DISTRIBUTION_FREQUENCY,
EXCLUDED.FOREX_SOURCE,
EXCLUDED.NAV_RATIO_METHOD,
EXCLUDED.IS_ACTIVE,
EXCLUDED.IS_DORMANT,
EXCLUDED.DORMANT_DATE,
EXCLUDED.FUND_STAMP_DUTY_BOURNE,
EXCLUDED.pan_or_tin,
EXCLUDED.domicile
);`,

  class_map: `
  INSERT INTO fund.class_plan_master(
id, client_id, fund_scheme_id, plan_code, plan_name, plan_desc, class_code, class_name, class_desc,sip_category, min_amount, max_amount, management_fee, performance_fee, hurdle_rate, performance_fee_percent, share_ratio, additional_fee, org_fee, gst_rate, preferred_return, carry_percent, catchup_percent, currency, face_value, isin_code, high_water_mark, is_active, amc_plan, fa_plan, setup_fees_percent,class_contribution_percentage, sub_class, sponsor_class_percent
)
SELECT
COALESCE(
cp.id,
case when length(tt.client_code)=2 then (ASCII(substring(tt.client_code,1,1))::text||ASCII(substring(tt.client_code,2,1))::text||ASCII(substring(tt.client_code,3,1))::text||ASCII(substring(upper(tt.fund_code),1,1))::text||ASCII(substring(upper(tt.fund_code),2,1))::text||ASCII(substring(upper(tt.class_code),1,1))::text||ASCII(substring(upper(tt.class_code),2,1))::text)::bigint else nextval('fund.class_plan_master_id_seq'::regclass) end
),
coalesce(cp.client_id, cc.id, (
SELECT
DISTINCT cc.id
FROM
fund.client_master cc
WHERE
upper(cc.client_code) = upper(tt.client_code)
)),
coalesce(cp.fund_scheme_id, sf.id, (
SELECT
DISTINCT sf.id
FROM
fund.fund_scheme_master sf
JOIN fund.client_master cc ON sf.client_id = cc.id
WHERE
upper(cc.client_code) = upper(tt.client_code)
AND upper(sf.fund_code) = upper(tt.fund_code)
)),
tt.plan_code,
tt.plan_name,
tt.plan_name plan_desc,

tt.class_code,
tt.class_name,
tt.class_desc class_desc,
(tt.class_category not ilike '%NON%'),
(
CASE
WHEN tt.min_amt ilike '%CR%'
OR tt.min_amt ilike '%LAC%' THEN replace(
replace(upper(tt.min_amt), ' CR', 'e7'),
' LAC',
'e5'
)
ELSE tt.min_amt
END
) :: numeric,
(
CASE
WHEN tt.max_amt ilike '%CR%'
OR tt.max_amt ilike '%LAC%' THEN replace(replace(tt.max_amt, ' CR', 'e7'), ' LAC', 'e5')
ELSE tt.max_amt
END
) :: numeric,
tt.management_fee :: numeric,
tt.performance_fee :: numeric,
tt.hurdle_rate :: numeric,
tt.performance_fee_percentage :: numeric,
tt.share_ratio :: numeric,
tt.additional_fee :: numeric,
tt.org_fee :: numeric,
tt.gst_rate :: numeric,
tt.preferred_return :: numeric,
tt.carry_percentage :: numeric,
tt.catchup_percentage :: numeric,
tt.currency,
tt.face_value :: numeric,
tt.isin_code,
tt.high_water_mark,
tt.is_active :: boolean,
tt.amc_plan,
tt.fa_plan,
tt.setup_fee_percentage :: numeric,
tt.class_contribution_percentage :: numeric,
tt.sub_class::text,
tt.sponsor_class_percent ::numeric
FROM
fund.class_plan_master cp
JOIN fund.fund_scheme_master sf ON cp.fund_scheme_id = sf.id and cp.client_id = sf.client_id
JOIN fund.client_master cc ON cp.client_id = cc.id
RIGHT JOIN stg.class_map tt ON upper(cc.client_code) = upper(tt.client_code) AND upper(sf.fund_code) = upper(tt.fund_code) AND upper(cp.class_code) = upper(tt.class_code)
WHERE tt.client_code = $1
AND ($2 IS NULL OR tt.fund_code = $2)
upper(tt.class_name) != upper(tt.fund_name)
and exists(select 1 from stg.client_map cm where cm.client_code=tt.client_code)
and exists(select 1 from STG.FUND_SCHEME_MAP fm where fm.client_code=tt.client_code and fm.fund_code=tt.fund_code)
and (cp.created_by not in ('finexdistsvc','xaltssvc') or cp.last_updated_by not in ('finexdistsvc','xaltssvc'))
and (sf.created_by not in ('finexdistsvc','xaltssvc') or sf.last_updated_by not in ('finexdistsvc','xaltssvc'))
and (cc.created_by not in ('finexdistsvc','xaltssvc') or cc.last_updated_by not in ('finexdistsvc','xaltssvc'))
ON CONFLICT(id) DO
UPDATE set (plan_code,plan_name,plan_desc,class_code,class_name,class_desc,sip_category,min_amount,max_amount,management_fee,performance_fee, hurdle_rate, performance_fee_percent, share_ratio, additional_fee, org_fee, gst_rate, preferred_return, carry_percent, catchup_percent, currency, face_value, isin_code, high_water_mark, is_active, amc_plan, fa_plan, setup_fees_percent,class_contribution_percentage, sub_class, sponsor_class_percent)=(EXCLUDED.plan_code,EXCLUDED.plan_name,EXCLUDED.plan_desc,EXCLUDED.class_code,EXCLUDED.class_name,EXCLUDED.class_desc,EXCLUDED.sip_category,EXCLUDED.min_amount,EXCLUDED.max_amount,EXCLUDED.management_fee, EXCLUDED.performance_fee, EXCLUDED.hurdle_rate, EXCLUDED.performance_fee_percent, EXCLUDED.share_ratio, EXCLUDED.additional_fee, EXCLUDED.org_fee, EXCLUDED.gst_rate, EXCLUDED.preferred_return, EXCLUDED.carry_percent, EXCLUDED.catchup_percent, EXCLUDED.currency, EXCLUDED.face_value, EXCLUDED.isin_code, EXCLUDED.high_water_mark, EXCLUDED.is_active, EXCLUDED.amc_plan, EXCLUDED.fa_plan, EXCLUDED.setup_fees_percent,EXCLUDED.class_contribution_percentage, EXCLUDED.sub_class, EXCLUDED.sponsor_class_percent);`,
  //  contact_map: ``,
  bank_map: `INSERT INTO fund.bank_master (
    id,
    client_id,
    fund_scheme_id,
    bank_name,
    bank_code,
    ifsc_code,
    currency,
    swift_code,
    corporate_id,
    branch_name,
    city,
    bank_account_name,
    bank_account_number,
    account_type,
    ownership_type,
    dormant_date
)
SELECT
    nextval('fund.bank_master_id_seq'::regclass) AS id,
    coalesce(cm.id, cm1.id) AS client_id,
    coalesce(sf.id, sf1.id) AS fund_scheme_id,
    bm.bank_name,
    bm.bank_code,
    bm.ifsc_code,
    bm.currency,
    bm.swift_code,
    bm.corporate_id,
    bm.branch_name,
    bm.city,
    bm.bank_account_name,
    bm.bank_account_number,
    bm.account_type,
    bm.ownership_type,
    to_date(bm.dormant_date, 'DD-MM-YYYY')
FROM
    stg.bank_map bm
LEFT JOIN fund.client_master cm ON bm.client_code = cm.client_code
LEFT JOIN fund.fund_scheme_master sf ON bm.fund_code = sf.fund_code AND cm.id = sf.client_id
LEFT JOIN fund.client_master cm1 ON bm.client_code = cm1.client_code
LEFT JOIN fund.fund_scheme_master sf1 ON cm1.id = sf1.client_id AND sf1.fund_code = bm.fund_code
WHERE cm.client_code = $1
AND (cm.created_by not in ('finexdistsvc','xaltssvc') or cm.last_updated_by not in ('finexdistsvc','xaltssvc'))
and (sf.created_by not in ('finexdistsvc','xaltssvc') or sf.last_updated_by not in ('finexdistsvc','xaltssvc'))
and (cm1.created_by not  in ('finexdistsvc','xaltssvc') or cm1.last_updated_by not in ('finexdistsvc','xaltssvc'))
and (sf1.created_by not in ('finexdistsvc','xaltssvc') or sf1.last_updated_by not in ('finexdistsvc','xaltssvc'))
ON CONFLICT (client_id, bank_name, bank_account_number, fund_scheme_id) DO UPDATE
SET
    client_id = EXCLUDED.client_id,
    fund_scheme_id = EXCLUDED.fund_scheme_id,
    bank_code = EXCLUDED.bank_code,
    ifsc_code = EXCLUDED.ifsc_code,
    currency = EXCLUDED.currency,
    swift_code = EXCLUDED.swift_code,
    corporate_id = EXCLUDED.corporate_id,
    branch_name = EXCLUDED.branch_name,
    city = EXCLUDED.city,
    bank_account_name = EXCLUDED.bank_account_name,
    account_type = EXCLUDED.account_type,
    ownership_type = EXCLUDED.ownership_type,
    dormant_date = EXCLUDED.dormant_date;`,
  drawdown_map: `...`,
} as const;
