/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadProcessorRouterRouteImport } from './routes/uploadProcessorRouter'
import { Route as SqlMongoRouterRouteImport } from './routes/sqlMongoRouter'
import { Route as SplitProcessorRouterRouteImport } from './routes/splitProcessorRouter'
import { Route as S3ManagerRouterRouteImport } from './routes/s3ManagerRouter'
import { Route as MasterMigrationRouterRouteImport } from './routes/masterMigrationRouter'
import { Route as DataCleanRouterRouteImport } from './routes/dataCleanRouter'
import { Route as IndexRouteImport } from './routes/index'

const UploadProcessorRouterRoute = UploadProcessorRouterRouteImport.update({
  id: '/uploadProcessorRouter',
  path: '/uploadProcessorRouter',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlMongoRouterRoute = SqlMongoRouterRouteImport.update({
  id: '/sqlMongoRouter',
  path: '/sqlMongoRouter',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitProcessorRouterRoute = SplitProcessorRouterRouteImport.update({
  id: '/splitProcessorRouter',
  path: '/splitProcessorRouter',
  getParentRoute: () => rootRouteImport,
} as any)
const S3ManagerRouterRoute = S3ManagerRouterRouteImport.update({
  id: '/s3ManagerRouter',
  path: '/s3ManagerRouter',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterMigrationRouterRoute = MasterMigrationRouterRouteImport.update({
  id: '/masterMigrationRouter',
  path: '/masterMigrationRouter',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCleanRouterRoute = DataCleanRouterRouteImport.update({
  id: '/dataCleanRouter',
  path: '/dataCleanRouter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dataCleanRouter': typeof DataCleanRouterRoute
  '/masterMigrationRouter': typeof MasterMigrationRouterRoute
  '/s3ManagerRouter': typeof S3ManagerRouterRoute
  '/splitProcessorRouter': typeof SplitProcessorRouterRoute
  '/sqlMongoRouter': typeof SqlMongoRouterRoute
  '/uploadProcessorRouter': typeof UploadProcessorRouterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dataCleanRouter': typeof DataCleanRouterRoute
  '/masterMigrationRouter': typeof MasterMigrationRouterRoute
  '/s3ManagerRouter': typeof S3ManagerRouterRoute
  '/splitProcessorRouter': typeof SplitProcessorRouterRoute
  '/sqlMongoRouter': typeof SqlMongoRouterRoute
  '/uploadProcessorRouter': typeof UploadProcessorRouterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dataCleanRouter': typeof DataCleanRouterRoute
  '/masterMigrationRouter': typeof MasterMigrationRouterRoute
  '/s3ManagerRouter': typeof S3ManagerRouterRoute
  '/splitProcessorRouter': typeof SplitProcessorRouterRoute
  '/sqlMongoRouter': typeof SqlMongoRouterRoute
  '/uploadProcessorRouter': typeof UploadProcessorRouterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dataCleanRouter'
    | '/masterMigrationRouter'
    | '/s3ManagerRouter'
    | '/splitProcessorRouter'
    | '/sqlMongoRouter'
    | '/uploadProcessorRouter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dataCleanRouter'
    | '/masterMigrationRouter'
    | '/s3ManagerRouter'
    | '/splitProcessorRouter'
    | '/sqlMongoRouter'
    | '/uploadProcessorRouter'
  id:
    | '__root__'
    | '/'
    | '/dataCleanRouter'
    | '/masterMigrationRouter'
    | '/s3ManagerRouter'
    | '/splitProcessorRouter'
    | '/sqlMongoRouter'
    | '/uploadProcessorRouter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataCleanRouterRoute: typeof DataCleanRouterRoute
  MasterMigrationRouterRoute: typeof MasterMigrationRouterRoute
  S3ManagerRouterRoute: typeof S3ManagerRouterRoute
  SplitProcessorRouterRoute: typeof SplitProcessorRouterRoute
  SqlMongoRouterRoute: typeof SqlMongoRouterRoute
  UploadProcessorRouterRoute: typeof UploadProcessorRouterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploadProcessorRouter': {
      id: '/uploadProcessorRouter'
      path: '/uploadProcessorRouter'
      fullPath: '/uploadProcessorRouter'
      preLoaderRoute: typeof UploadProcessorRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sqlMongoRouter': {
      id: '/sqlMongoRouter'
      path: '/sqlMongoRouter'
      fullPath: '/sqlMongoRouter'
      preLoaderRoute: typeof SqlMongoRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splitProcessorRouter': {
      id: '/splitProcessorRouter'
      path: '/splitProcessorRouter'
      fullPath: '/splitProcessorRouter'
      preLoaderRoute: typeof SplitProcessorRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3ManagerRouter': {
      id: '/s3ManagerRouter'
      path: '/s3ManagerRouter'
      fullPath: '/s3ManagerRouter'
      preLoaderRoute: typeof S3ManagerRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterMigrationRouter': {
      id: '/masterMigrationRouter'
      path: '/masterMigrationRouter'
      fullPath: '/masterMigrationRouter'
      preLoaderRoute: typeof MasterMigrationRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataCleanRouter': {
      id: '/dataCleanRouter'
      path: '/dataCleanRouter'
      fullPath: '/dataCleanRouter'
      preLoaderRoute: typeof DataCleanRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataCleanRouterRoute: DataCleanRouterRoute,
  MasterMigrationRouterRoute: MasterMigrationRouterRoute,
  S3ManagerRouterRoute: S3ManagerRouterRoute,
  SplitProcessorRouterRoute: SplitProcessorRouterRoute,
  SqlMongoRouterRoute: SqlMongoRouterRoute,
  UploadProcessorRouterRoute: UploadProcessorRouterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
