/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadProcessorRouterRouteImport } from './routes/uploadProcessorRouter'
import { Route as SqlMongoRouteImport } from './routes/sql-mongo'
import { Route as SplitProcessorRouterRouteImport } from './routes/splitProcessorRouter'
import { Route as SanityCheckRouteImport } from './routes/sanity-check'
import { Route as S3BrowserRouteImport } from './routes/s3ManagerRouter'
import { Route as IndexRouteImport } from './routes/index'

const UploadProcessorRouterRoute = UploadProcessorRouterRouteImport.update({
  id: '/uploadProcessorRouter',
  path: '/uploadProcessorRouter',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlMongoRoute = SqlMongoRouteImport.update({
  id: '/sql-mongo',
  path: '/sql-mongo',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitProcessorRouterRoute = SplitProcessorRouterRouteImport.update({
  id: '/splitProcessorRouter',
  path: '/splitProcessorRouter',
  getParentRoute: () => rootRouteImport,
} as any)
const SanityCheckRoute = SanityCheckRouteImport.update({
  id: '/sanity-check',
  path: '/sanity-check',
  getParentRoute: () => rootRouteImport,
} as any)
const S3BrowserRoute = S3BrowserRouteImport.update({
  id: '/s3ManagerRouter',
  path: '/s3ManagerRouter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s3ManagerRouter': typeof S3BrowserRoute
  '/sanity-check': typeof SanityCheckRoute
  '/splitProcessorRouter': typeof SplitProcessorRouterRoute
  '/sql-mongo': typeof SqlMongoRoute
  '/uploadProcessorRouter': typeof UploadProcessorRouterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s3ManagerRouter': typeof S3BrowserRoute
  '/sanity-check': typeof SanityCheckRoute
  '/splitProcessorRouter': typeof SplitProcessorRouterRoute
  '/sql-mongo': typeof SqlMongoRoute
  '/uploadProcessorRouter': typeof UploadProcessorRouterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s3ManagerRouter': typeof S3BrowserRoute
  '/sanity-check': typeof SanityCheckRoute
  '/splitProcessorRouter': typeof SplitProcessorRouterRoute
  '/sql-mongo': typeof SqlMongoRoute
  '/uploadProcessorRouter': typeof UploadProcessorRouterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/s3ManagerRouter'
    | '/sanity-check'
    | '/splitProcessorRouter'
    | '/sql-mongo'
    | '/uploadProcessorRouter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/s3ManagerRouter'
    | '/sanity-check'
    | '/splitProcessorRouter'
    | '/sql-mongo'
    | '/uploadProcessorRouter'
  id:
    | '__root__'
    | '/'
    | '/s3ManagerRouter'
    | '/sanity-check'
    | '/splitProcessorRouter'
    | '/sql-mongo'
    | '/uploadProcessorRouter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  S3BrowserRoute: typeof S3BrowserRoute
  SanityCheckRoute: typeof SanityCheckRoute
  SplitProcessorRouterRoute: typeof SplitProcessorRouterRoute
  SqlMongoRoute: typeof SqlMongoRoute
  UploadProcessorRouterRoute: typeof UploadProcessorRouterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploadProcessorRouter': {
      id: '/uploadProcessorRouter'
      path: '/uploadProcessorRouter'
      fullPath: '/uploadProcessorRouter'
      preLoaderRoute: typeof UploadProcessorRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-mongo': {
      id: '/sql-mongo'
      path: '/sql-mongo'
      fullPath: '/sql-mongo'
      preLoaderRoute: typeof SqlMongoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splitProcessorRouter': {
      id: '/splitProcessorRouter'
      path: '/splitProcessorRouter'
      fullPath: '/splitProcessorRouter'
      preLoaderRoute: typeof SplitProcessorRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanity-check': {
      id: '/sanity-check'
      path: '/sanity-check'
      fullPath: '/sanity-check'
      preLoaderRoute: typeof SanityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3ManagerRouter': {
      id: '/s3ManagerRouter'
      path: '/s3ManagerRouter'
      fullPath: '/s3ManagerRouter'
      preLoaderRoute: typeof S3BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  S3BrowserRoute: S3BrowserRoute,
  SanityCheckRoute: SanityCheckRoute,
  SplitProcessorRouterRoute: SplitProcessorRouterRoute,
  SqlMongoRoute: SqlMongoRoute,
  UploadProcessorRouterRoute: UploadProcessorRouterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
